import { createServer, type IncomingMessage, type Server, type ServerResponse } from "node:http";
import { readFile } from "node:fs/promises";
import { join, normalize, resolve } from "node:path";
import { expect, test } from "playwright/test";

type Account = { id: string; name: string; enabled: boolean; priority: number; daily_point_limit: number; monthly_point_limit: number; daily_used_points: number; monthly_used_points: number; daily_reserved_points: number; monthly_reserved_points: number; health_status: "ready"; last_error_code: null; has_session: boolean; points_balance: number; total_balance: number; active_jobs: number; updated_at: number };
let server: Server | undefined;
let accounts: Account[] = [];
let nextId = 1;
let signedIn = false;
const output = resolve(process.cwd(), "dist", "admin");

function overview() { return { accounts: { total: accounts.length, enabled: accounts.filter((item) => item.enabled).length, ready: accounts.length, unhealthy: 0, budget_exhausted: 0 }, usage: { daily_used_points: 0, monthly_used_points: 0, daily_reserved_points: 0, monthly_reserved_points: 0 }, jobs: { active: 0, queued: 0 }, recent_failures: [] }; }
function json(response: ServerResponse, payload: unknown, status = 200) { response.writeHead(status, { "Content-Type": "application/json", "Cache-Control": "no-store" }); response.end(JSON.stringify(payload)); }
async function body(request: IncomingMessage): Promise<Record<string, unknown>> { let value = ""; for await (const part of request) value += String(part); return value ? JSON.parse(value) as Record<string, unknown> : {}; }
function safeAsset(pathname: string): string | null { const relative = pathname.replace(/^\/admin\/assets\//, ""); const filename = normalize(join(output, "assets", relative)); return filename.startsWith(join(output, "assets")) ? filename : null; }

test.beforeAll(async () => {
  server = createServer(async (request, response) => {
    const url = new URL(request.url ?? "/", "http://127.0.0.1:4174");
    if (url.pathname === "/admin/api/login" && request.method === "POST") { signedIn = true; json(response, { authenticated: true, csrf_token: "fixture-csrf", expires_at: 9_999_999_999_999 }, 200); return; }
    if (url.pathname === "/admin/api/session") { if (!signedIn) { json(response, { error: { code: "unauthorized" } }, 401); return; } json(response, { authenticated: true, csrf_token: "fixture-csrf", expires_at: 9_999_999_999_999 }); return; }
    if (url.pathname === "/admin/api/accounts" && request.method === "GET") { json(response, { accounts }); return; }
    if (url.pathname === "/admin/api/overview") { json(response, overview()); return; }
    if (url.pathname === "/admin/api/jobs") { json(response, { jobs: [] }); return; }
    if (url.pathname === "/admin/api/settings") { json(response, { max_concurrency: 5, max_queued_requests: 20, unknown_capacity_hold_ms: 900000, image_wait_timeout_ms: 300000, video_wait_timeout_ms: 900000, docs_enabled: false }); return; }
    if (url.pathname === "/admin/api/accounts" && request.method === "POST") { const input = await body(request); const account: Account = { id: `browser-${nextId++}`, name: String(input.name), enabled: true, priority: Number(input.priority), daily_point_limit: Number(input.daily_point_limit), monthly_point_limit: Number(input.monthly_point_limit), daily_used_points: 0, monthly_used_points: 0, daily_reserved_points: 0, monthly_reserved_points: 0, health_status: "ready", last_error_code: null, has_session: false, points_balance: 120, total_balance: 120, active_jobs: 0, updated_at: Date.now() }; accounts = [...accounts, account]; json(response, { account, login_command: `npm run login -- --account-id ${account.id}` }, 201); return; }
    const match = /^\/admin\/api\/accounts\/([^/]+)\/(enable|disable)$/.exec(url.pathname);
    if (match !== null && request.method === "POST") { accounts = accounts.map((account) => account.id === match[1] ? { ...account, enabled: match[2] === "enable" } : account); json(response, { account: accounts.find((account) => account.id === match[1]) }); return; }
    const edit = /^\/admin\/api\/accounts\/([^/]+)$/.exec(url.pathname);
    if (edit !== null && request.method === "PATCH") { const input = await body(request); accounts = accounts.map((account) => account.id === edit[1] ? { ...account, name: String(input.name), priority: Number(input.priority), daily_point_limit: Number(input.daily_point_limit), monthly_point_limit: Number(input.monthly_point_limit) } : account); json(response, { account: accounts.find((account) => account.id === edit[1]) }); return; }
    if (url.pathname.startsWith("/admin/assets/")) { const file = safeAsset(url.pathname); if (file !== null) { try { response.writeHead(200, { "Content-Type": file.endsWith(".css") ? "text/css" : "application/javascript" }); response.end(await readFile(file)); return; } catch { json(response, { error: "not_found" }, 404); return; } } }
    if (["/admin", "/admin/", "/admin/accounts", "/admin/tasks", "/admin/settings"].includes(url.pathname)) { response.writeHead(200, { "Content-Type": "text/html", "Cache-Control": "no-store" }); response.end(await readFile(join(output, "index.html"))); return; }
    json(response, { error: "not_found" }, 404);
  });
  await new Promise<void>((resolveServer) => server!.listen(4174, "127.0.0.1", resolveServer));
});
test.afterAll(async () => await new Promise<void>((resolveServer) => server?.close(() => resolveServer())));
test.beforeEach(() => { signedIn = false; });

for (const viewport of [{ name: "desktop", width: 1440, height: 900 }, { name: "mobile", width: 390, height: 844 }] as const) test(`operator manages an account without horizontal overflow (${viewport.name})`, async ({ page }, testInfo) => { const navigate = async (next: "overview" | "tasks") => { if (viewport.name === "desktop") await page.getByRole("link", { name: next === "overview" ? "Overview" : "Tasks" }).click(); else await page.getByLabel("Navigate").selectOption(next); }; await page.setViewportSize(viewport); await page.goto("http://127.0.0.1:4174/admin/"); await expect(page.getByRole("heading", { name: "Admin sign in" })).toBeVisible(); await page.screenshot({ path: testInfo.outputPath("login.png"), fullPage: true }); await page.getByLabel("Administrator password").fill("fixture-admin-password"); await page.getByRole("button", { name: "Sign in" }).click(); await expect(page.getByRole("heading", { name: "Accounts" })).toBeVisible(); await page.getByRole("button", { name: "Create account" }).click(); await page.getByLabel("Account name").fill(`Browser ${viewport.name}`); await page.getByLabel("Priority").fill("7"); await page.getByLabel("Daily point limit").fill("10"); await page.getByLabel("Monthly point limit").fill("100"); await page.getByRole("button", { name: "Create account" }).last().click(); await expect(page.getByText("npm run login -- --account-id")).toBeVisible(); await page.getByRole("button", { name: "Copy login command" }).click(); await expect(page.getByText("Login command copied")).toBeVisible(); await page.getByRole("button", { name: `Edit Browser ${viewport.name}` }).click(); await page.getByLabel("Priority").fill("3"); await page.getByLabel("Daily point limit").fill("25"); await page.getByLabel("Monthly point limit").fill("250"); await page.getByRole("button", { name: "Save account" }).click(); await expect(page.getByText("0 / 250", { exact: true })).toBeVisible(); await page.getByRole("button", { name: `Disable Browser ${viewport.name}` }).click(); await expect(page.getByText("Disabled", { exact: true })).toBeVisible(); await page.getByRole("button", { name: `Enable Browser ${viewport.name}` }).click(); await expect(page.getByText("Enabled", { exact: true })).toBeVisible(); await page.screenshot({ path: testInfo.outputPath("accounts.png"), fullPage: true }); await navigate("overview"); await expect(page.getByText("Ready accounts")).toBeVisible(); await page.screenshot({ path: testInfo.outputPath("overview.png"), fullPage: true }); await navigate("tasks"); await page.getByLabel("Account filter").selectOption({ label: `Browser ${viewport.name}` }); await page.getByLabel("Kind filter").selectOption("image"); await page.getByLabel("Status filter").selectOption("queued"); await expect(page.getByText("No tasks match these filters")).toBeVisible(); await expect(page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).resolves.toBe(true); });
