import { randomBytes } from "node:crypto";
import type { SqliteStore } from "../persistence/sqlite-store.js";

export interface PlanRecord { id:string; name:string; enabled:boolean; allowedModes:("text-to-video"|"image-to-video")[]; allowedModels:string[]; maxDurationSeconds:number; allowedResolutions:string[]; dailyLimitPoints:number; monthlyLimitPoints:number; maxConcurrency:number; maxQueuedRequests:number; createdAt:number; updatedAt:number; }
interface Row { id:string;name:string;enabled:number;allowed_modes_json:string;allowed_models_json:string;max_duration_seconds:number;allowed_resolutions_json:string;daily_limit_points:number;monthly_limit_points:number;max_concurrency:number;max_queued_requests:number;created_at:number;updated_at:number }
function strings(value:string):string[]{const parsed:unknown=JSON.parse(value);if(!Array.isArray(parsed)||parsed.some((v)=>typeof v!=="string"))throw new Error("Plan JSON invalid");return parsed as string[];}
function fromRow(r:Row):PlanRecord{return{id:r.id,name:r.name,enabled:r.enabled===1,allowedModes:strings(r.allowed_modes_json) as PlanRecord["allowedModes"],allowedModels:strings(r.allowed_models_json),maxDurationSeconds:r.max_duration_seconds,allowedResolutions:strings(r.allowed_resolutions_json),dailyLimitPoints:r.daily_limit_points,monthlyLimitPoints:r.monthly_limit_points,maxConcurrency:r.max_concurrency,maxQueuedRequests:r.max_queued_requests,createdAt:r.created_at,updatedAt:r.updated_at};}
export class SqlitePlanRepository{
 constructor(private readonly store:SqliteStore){}
 create(input:Omit<PlanRecord,"id"|"createdAt"|"updatedAt">):PlanRecord{return this.store.immediate(db=>{const id=`plan_${randomBytes(12).toString("hex")}`,now=Date.now();db.prepare(`INSERT INTO plans(id,name,enabled,allowed_modes_json,allowed_models_json,max_duration_seconds,allowed_resolutions_json,daily_limit_points,monthly_limit_points,max_concurrency,max_queued_requests,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.name.trim(),input.enabled?1:0,JSON.stringify(input.allowedModes),JSON.stringify(input.allowedModels),input.maxDurationSeconds,JSON.stringify(input.allowedResolutions),input.dailyLimitPoints,input.monthlyLimitPoints,input.maxConcurrency,input.maxQueuedRequests,now,now);return this.require(db,id);});}
 list():PlanRecord[]{return this.store.read(db=>(db.prepare("SELECT * FROM plans ORDER BY created_at,id").all() as Row[]).map(fromRow));}
 assign(projectId:string,planId:string):void{this.store.immediate(db=>{const plan=db.prepare("SELECT enabled FROM plans WHERE id=?").get(planId) as {enabled:number}|undefined;if(plan?.enabled!==1)throw new Error("Active plan not found");if(db.prepare("UPDATE projects SET plan_id=?,updated_at=? WHERE id=?").run(planId,Date.now(),projectId).changes!==1)throw new Error("Project not found");});}
 policy(projectId:string):PlanRecord|null{return this.store.read(db=>{const row=db.prepare("SELECT pl.* FROM plans pl JOIN projects p ON p.plan_id=pl.id WHERE p.id=? AND p.status='active' AND pl.enabled=1").get(projectId) as Row|undefined;return row?fromRow(row):null;});}
 assertVideo(projectId:string,input:{mode:"text-to-video"|"image-to-video";model:string;duration?:number;resolution?:string}):void{const plan=this.policy(projectId);if(!plan)throw new Error("Active project plan not found");if(!plan.allowedModes.includes(input.mode))throw new Error("Plan does not allow this video mode");if(plan.allowedModels.length&& !plan.allowedModels.includes(input.model))throw new Error("Plan does not allow this model");if(plan.maxDurationSeconds&&input.duration!==undefined&&input.duration>plan.maxDurationSeconds)throw new Error("Plan duration limit exceeded");if(plan.allowedResolutions.length&&input.resolution!==undefined&&!plan.allowedResolutions.includes(input.resolution))throw new Error("Plan does not allow this resolution");}
 private require(db:import("better-sqlite3").Database,id:string):PlanRecord{const row=db.prepare("SELECT * FROM plans WHERE id=?").get(id) as Row|undefined;if(!row)throw new Error("Plan not found");return fromRow(row);}
}
