import type { Account } from "../types";
import { BudgetMeter } from "../components/budget-meter";
import { StatusPill } from "../components/status-pill";

function refreshedAt(value: number | null): string {
  return value === null ? "Not refreshed yet" : new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(value);
}

export function AccountsPage({ accounts, onCreate, onEdit, onToggle, onCheck,onLogin, checking,loggingIn }: { accounts: Account[]; onCreate(): void; onEdit(account: Account): void; onToggle(account: Account): void; onCheck(account: Account): void;onLogin(account:Account):void; checking: string | null;loggingIn:string|null }) {
  return <><header className="page-heading"><div><p className="eyebrow">Work queue</p><h1>Accounts</h1><p>Wallet balance and operating budgets remain separate.</p></div><button onClick={onCreate}>Add account</button></header><section className="data-region accounts-region" aria-busy={false}>{accounts.length === 0 ? <p className="empty-state">No accounts yet. Add the first account to begin.</p> : <div className="account-list">{accounts.map((account) => <article className="account-row" key={account.id}><div className="account-name"><strong>{account.name}</strong><span className="mono">{account.id}</span><StatusPill status={account.health_status} /></div><div className="balance-facts"><span>{account.membership ?? "No membership data"}</span><strong>Points {account.points_balance ?? "—"}</strong><strong>Total balance {account.total_balance ?? "—"}</strong><span>Last refreshed {refreshedAt(account.last_checked_at)}</span></div><BudgetMeter label="Daily" used={account.daily_used_points} reserved={account.daily_reserved_points} limit={account.daily_point_limit} /><BudgetMeter label="Monthly" used={account.monthly_used_points} reserved={account.monthly_reserved_points} limit={account.monthly_point_limit} /><div className="account-meta"><span>Priority {account.priority}</span><span>{account.active_jobs} active</span></div><div className="row-actions"><button className="quiet-button" aria-label={`Login ${account.name}`} disabled={loggingIn===account.id} onClick={()=>onLogin(account)}>{loggingIn===account.id?"Waiting for browser…":account.has_session?"Re-login":"Login in browser"}</button><button className="quiet-button" aria-label={`Refresh balance ${account.name}`} disabled={checking === account.id} onClick={() => onCheck(account)}>{checking === account.id ? "Refreshing…" : "Refresh balance"}</button><button className="quiet-button" aria-label={`Edit ${account.name}`} onClick={() => onEdit(account)}>Edit</button><button className={account.enabled ? "danger-button" : "quiet-button"} aria-label={`${account.enabled ? "Disable" : "Enable"} ${account.name}`} onClick={() => onToggle(account)}>{account.enabled ? "Disable" : "Enable"}</button><span className="enabled-label">{account.enabled ? "Enabled" : "Disabled"}</span></div></article>)}</div>}</section></>;
}
