import { useMemo, useState } from "react";
import type { Project, UsageData, User } from "../types";

export function UsagePage({ data, users, projects, onFilter }: { data:UsageData; users:User[]; projects:Project[]; onFilter(filters:{user_id?:string;project_id?:string}):Promise<void> }) {
  const [userId,setUserId]=useState(""); const [projectId,setProjectId]=useState("");
  const visibleProjects=useMemo(()=>projects.filter((p)=>!userId||p.user_id===userId),[projects,userId]);
  const filter=async()=>onFilter({...(userId?{user_id:userId}:{}),...(projectId?{project_id:projectId}:{})});
  return <><header className="page-heading"><div><p className="eyebrow">Downstream accounting</p><h1 tabIndex={-1}>Usage</h1><p>Trace holds, charges and releases without conflating upstream balance.</p></div></header><div className="filters"><label>User<select value={userId} onChange={(e)=>{setUserId(e.target.value);setProjectId("");}}><option value="">All users</option>{users.map((u)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Project<select value={projectId} onChange={(e)=>setProjectId(e.target.value)}><option value="">All projects</option>{visibleProjects.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={()=>void filter()}>Apply filters</button></div><section className="overview-strip usage-summary"><div><span>Charged</span><strong>{data.summary.charged_points}</strong></div><div><span>Released</span><strong>{data.summary.released_points}</strong></div><div><span>Net points</span><strong>{data.summary.net_points}</strong></div><div><span>Ledger entries</span><strong>{data.summary.entry_count}</strong></div></section><section className="data-region"><h2>Ledger</h2>{data.entries.length===0?<p className="empty-state">No usage entries match these filters.</p>:<table className="tasks-table"><thead><tr><th>Time</th><th>Project</th><th>Type</th><th>Reason</th><th>Job</th><th className="numeric">Points</th></tr></thead><tbody>{data.entries.map((entry)=><tr key={entry.id}><td data-label="Time">{new Date(entry.created_at).toLocaleString()}</td><td data-label="Project">{projects.find((p)=>p.id===entry.project_id)?.name??entry.project_id}</td><td data-label="Type">{entry.type}</td><td data-label="Reason">{entry.reason.replaceAll("_"," ")}</td><td data-label="Job"><code>{entry.job_id}</code></td><td className="numeric" data-label="Points">{entry.points}</td></tr>)}</tbody></table>}</section></>;
}
