import { useMemo, useState } from "react";
import type { Project, UsageData, User } from "../types";

export function UsagePage({ data, users, projects, onFilter }: { data:UsageData; users:User[]; projects:Project[]; onFilter(filters:{user_id?:string;project_id?:string}):Promise<void> }) {
  const [userId,setUserId]=useState(""); const [projectId,setProjectId]=useState("");
  const visibleProjects=useMemo(()=>projects.filter((p)=>!userId||p.user_id===userId),[projects,userId]);
  const filter=async()=>onFilter({...(userId?{user_id:userId}:{}),...(projectId?{project_id:projectId}:{})});
  return <><header className="page-heading"><div><p className="eyebrow">下游计量</p><h1 tabIndex={-1}>用量</h1><p>追踪预留、扣费和释放记录，不与上游余额混淆。</p></div></header><div className="filters"><label>用户<select value={userId} onChange={(e)=>{setUserId(e.target.value);setProjectId("");}}><option value="">全部用户</option>{users.map((u)=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>项目<select value={projectId} onChange={(e)=>setProjectId(e.target.value)}><option value="">全部项目</option>{visibleProjects.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button onClick={()=>void filter()}>应用筛选</button></div><section className="overview-strip usage-summary"><div><span>已扣费</span><strong>{data.summary.charged_points}</strong></div><div><span>已释放</span><strong>{data.summary.released_points}</strong></div><div><span>净点数</span><strong>{data.summary.net_points}</strong></div><div><span>账本条目</span><strong>{data.summary.entry_count}</strong></div></section><section className="data-region"><h2>账本</h2>{data.entries.length===0?<p className="empty-state">没有符合当前筛选条件的用量记录。</p>:<table className="tasks-table"><thead><tr><th>时间</th><th>项目</th><th>类型</th><th>原因</th><th>任务</th><th className="numeric">点数</th></tr></thead><tbody>{data.entries.map((entry)=><tr key={entry.id}><td data-label="时间">{new Date(entry.created_at).toLocaleString("zh-CN")}</td><td data-label="项目">{projects.find((p)=>p.id===entry.project_id)?.name??entry.project_id}</td><td data-label="类型">{entry.type}</td><td data-label="原因">{entry.reason.replaceAll("_"," ")}</td><td data-label="任务"><code>{entry.job_id}</code></td><td className="numeric" data-label="点数">{entry.points}</td></tr>)}</tbody></table>}</section></>;
}
