import type{Pool}from"pg";export interface PostgresMigration{version:number;name:string;sql:string;}export async function migratePostgres(pool:Pool,migrations:readonly PostgresMigration[]):Promise<number>{const client=await pool.connect();try{await client.query("SELECT pg_advisory_lock($1)",[0x4c4a4757]);await client.query("CREATE TABLE IF NOT EXISTS schema_migrations(version integer PRIMARY KEY,name text NOT NULL,applied_at bigint NOT NULL)");const currentResult=await client.query<{version:number}>("SELECT COALESCE(MAX(version),0)::integer version FROM schema_migrations"),current=currentResult.rows[0]?.version??0;for(const migration of [...migrations].sort((a,b)=>a.version-b.version)){if(migration.version<=current)continue;await client.query("BEGIN");try{await client.query(migration.sql);await client.query("INSERT INTO schema_migrations(version,name,applied_at) VALUES($1,$2,$3)",[migration.version,migration.name,Date.now()]);await client.query("COMMIT");}catch(cause){await client.query("ROLLBACK");throw cause;}}const result=await client.query<{version:number}>("SELECT COALESCE(MAX(version),0)::integer version FROM schema_migrations");return result.rows[0]?.version??0;}finally{await client.query("SELECT pg_advisory_unlock($1)",[0x4c4a4757]).catch(()=>undefined);client.release();}}
export const corePostgresMigrations:readonly PostgresMigration[]=[{version:1,name:"core-runtime",sql:`CREATE TABLE users(id text PRIMARY KEY,name text UNIQUE NOT NULL,status text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL);CREATE TABLE plans(id text PRIMARY KEY,name text UNIQUE NOT NULL,enabled boolean NOT NULL,allowed_modes jsonb NOT NULL DEFAULT '[]',allowed_models jsonb NOT NULL DEFAULT '[]',max_duration_seconds integer NOT NULL DEFAULT 60,allowed_resolutions jsonb NOT NULL DEFAULT '[]',daily_limit_points numeric NOT NULL,monthly_limit_points numeric NOT NULL,max_concurrency integer NOT NULL DEFAULT 5,max_queued_requests integer NOT NULL DEFAULT 20,created_at bigint NOT NULL,updated_at bigint NOT NULL);CREATE TABLE projects(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),plan_id text NOT NULL REFERENCES plans(id),name text NOT NULL,status text NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL,UNIQUE(user_id,name));CREATE TABLE accounts(id text PRIMARY KEY,name text UNIQUE NOT NULL,enabled boolean NOT NULL,priority integer NOT NULL,daily_point_limit numeric NOT NULL,monthly_point_limit numeric NOT NULL,max_concurrency integer NOT NULL,health_status text NOT NULL,last_error_code text,membership text,points_balance numeric,total_balance numeric,last_checked_at bigint,created_at bigint NOT NULL,updated_at bigint NOT NULL);CREATE TABLE jobs(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),project_id text NOT NULL REFERENCES projects(id),api_key_id text,account_id text NOT NULL REFERENCES accounts(id),kind text NOT NULL,source_type text NOT NULL,model text NOT NULL,api_id text,model_code text,space_id integer,upstream_fingerprint text,submitted_at bigint,request_fingerprint text NOT NULL,idempotency_key_hash text,status text NOT NULL,quoted_points numeric NOT NULL,quote_known boolean NOT NULL,result_json jsonb,error_code text,upstream_task_id text,reconcile_after bigint,processing_deadline_at bigint,archive_status text NOT NULL DEFAULT 'none',archive_retry_at bigint,recovery_claim_token text,recovery_claimed_by text,recovery_claim_expires_at bigint,created_at bigint NOT NULL,updated_at bigint NOT NULL);CREATE INDEX jobs_worker_active_idx ON jobs(status,updated_at);
CREATE UNIQUE INDEX jobs_idempotency_unique ON jobs(api_key_id,idempotency_key_hash) WHERE idempotency_key_hash IS NOT NULL;CREATE TABLE job_status_history(job_id text REFERENCES jobs(id),status text NOT NULL,created_at bigint NOT NULL);CREATE TABLE job_worker_leases(job_id text PRIMARY KEY REFERENCES jobs(id),worker_id text NOT NULL,lease_token text UNIQUE NOT NULL,fencing_token bigint NOT NULL,lease_expires_at bigint NOT NULL,heartbeat_at bigint NOT NULL,acquired_at bigint NOT NULL,updated_at bigint NOT NULL);`},{version:2,name:"execution-assets-webhooks",sql:`
CREATE TABLE budget_entries(job_id text PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,account_id text NOT NULL REFERENCES accounts(id),quoted_points numeric NOT NULL,state text NOT NULL CHECK(state IN('reserved','charged','released')),day_window_start bigint NOT NULL,month_window_start bigint NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL);
CREATE TABLE usage_ledger(id text PRIMARY KEY,job_id text NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,user_id text NOT NULL REFERENCES users(id),project_id text NOT NULL REFERENCES projects(id),api_key_id text,account_id text NOT NULL REFERENCES accounts(id),entry_type text NOT NULL,points numeric NOT NULL,reason text NOT NULL,created_at bigint NOT NULL,UNIQUE(job_id,entry_type,reason));
CREATE TABLE provider_submissions(id text PRIMARY KEY,job_id text NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE CASCADE,account_id text NOT NULL REFERENCES accounts(id),request_fingerprint text NOT NULL,upstream_fingerprint text NOT NULL,catalog_revision text NOT NULL,baseline_json jsonb NOT NULL,outcome text NOT NULL,ambiguity_reason text,created_at bigint NOT NULL,updated_at bigint NOT NULL);
CREATE TABLE provider_correlations(id text PRIMARY KEY,submission_id text NOT NULL UNIQUE REFERENCES provider_submissions(id) ON DELETE CASCADE,job_id text NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE CASCADE,provider text NOT NULL,account_id text NOT NULL REFERENCES accounts(id),upstream_task_id text,upstream_asset_id text,creation_code text,evidence_type text NOT NULL,confidence text NOT NULL,correlated_at bigint NOT NULL);
CREATE UNIQUE INDEX provider_task_unique ON provider_correlations(provider,account_id,upstream_task_id) WHERE upstream_task_id IS NOT NULL;
CREATE TABLE job_request_snapshots(job_id text PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,payload_json jsonb NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL);
CREATE TABLE job_assets(id text PRIMARY KEY,job_id text REFERENCES jobs(id),user_id text NOT NULL REFERENCES users(id),project_id text NOT NULL REFERENCES projects(id),role text NOT NULL CHECK(role IN('input','output','poster')),storage_key text NOT NULL UNIQUE,sha256 text NOT NULL,mime_type text NOT NULL,filename text NOT NULL,size_bytes bigint NOT NULL,expires_at bigint,created_at bigint NOT NULL);
CREATE TABLE pending_uploads(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),project_id text NOT NULL REFERENCES projects(id),storage_key text NOT NULL UNIQUE,filename text NOT NULL,content_type text NOT NULL,size_bytes bigint NOT NULL,status text NOT NULL CHECK(status IN('pending','completed')),expires_at bigint NOT NULL,created_at bigint NOT NULL,completed_at bigint);
CREATE TABLE api_keys(id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),project_id text NOT NULL REFERENCES projects(id),name text NOT NULL,key_hash text NOT NULL,key_salt text NOT NULL,scopes_json jsonb NOT NULL,status text NOT NULL CHECK(status IN('active','disabled','revoked')),expires_at bigint,created_at bigint NOT NULL,updated_at bigint NOT NULL);
CREATE INDEX api_keys_principal_idx ON api_keys(user_id,project_id,status);
CREATE TABLE webhook_endpoints(id text PRIMARY KEY,project_id text NOT NULL UNIQUE REFERENCES projects(id),url text NOT NULL,secret_hash text NOT NULL,enabled boolean NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL);
CREATE TABLE webhook_outbox(id text PRIMARY KEY,project_id text NOT NULL REFERENCES projects(id),job_id text NOT NULL REFERENCES jobs(id),event_type text NOT NULL,payload_json jsonb NOT NULL,status text NOT NULL,attempts integer NOT NULL DEFAULT 0,next_attempt_at bigint NOT NULL,last_error text,delivered_at bigint,claim_token text,claimed_by text,claim_expires_at bigint,created_at bigint NOT NULL,updated_at bigint NOT NULL,UNIQUE(job_id,event_type));
CREATE INDEX budget_account_windows_idx ON budget_entries(account_id,day_window_start,month_window_start,state);
CREATE INDEX assets_expiry_idx ON job_assets(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX pending_uploads_expiry_idx ON pending_uploads(status,expires_at);
CREATE INDEX webhook_due_idx ON webhook_outbox(status,next_attempt_at);
`},{version:3,name:"compatibility-columns",sql:`
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_error_code text;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS membership text;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS points_balance numeric;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS total_balance numeric;
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS last_checked_at bigint;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS api_id text;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS model_code text;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS space_id integer;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS upstream_fingerprint text;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS submitted_at bigint;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS recovery_claim_token text;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS recovery_claimed_by text;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS recovery_claim_expires_at bigint;
CREATE TABLE IF NOT EXISTS job_request_snapshots(job_id text PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,payload_json jsonb NOT NULL,created_at bigint NOT NULL,updated_at bigint NOT NULL);
CREATE INDEX IF NOT EXISTS jobs_worker_active_idx ON jobs(status,updated_at);
CREATE INDEX IF NOT EXISTS recovery_claim_idx ON jobs(recovery_claim_expires_at,updated_at);
`}];
