import{createHash}from"node:crypto";import Database from"better-sqlite3";import type{Pool,PoolClient}from"pg";export interface MigrationReport{tables:Record<string,number>;checksums:Record<string,string>;targetChecksums:Record<string,string>;objectKeys:string[];}
const TABLES=["users","plans","projects","accounts","api_keys","jobs","job_status_history","budget_entries","usage_ledger","provider_submissions","provider_correlations","job_assets","pending_uploads","webhook_endpoints","webhook_outbox"]as const;
export async function migrateSqliteToPostgres(sqlitePath:string,pool:Pool,options:{dryRun?:boolean;requireEmptyTarget?:boolean}={}):Promise<MigrationReport>{const source=new Database(sqlitePath,{readonly:true}),client=await pool.connect(),report:MigrationReport={tables:{},checksums:{},targetChecksums:{},objectKeys:[]};try{await client.query("BEGIN");if(options.requireEmptyTarget===true)await assertEmptyTarget(client);for(const table of TABLES){if(!hasTable(source,table)){report.tables[table]=0;continue;}const columns=new Set((await client.query<{column_name:string}>("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1",[table])).rows.map(row=>row.column_name));const rows=source.prepare(`SELECT * FROM ${table}`).all()as Record<string,unknown>[];if(options.dryRun!==true)for(const row of rows)await insertRow(client,table,row,columns);report.tables[table]=rows.length;if(table==="job_assets")report.objectKeys=rows.map(row=>row["storage_key"]).filter((key):key is string=>typeof key==="string").sort();report.checksums[table]=createHash("sha256").update(JSON.stringify(rows,(_key,value:unknown):unknown=>Buffer.isBuffer(value)?value.toString("hex"):value)).digest("hex");}if(options.dryRun!==true){await validate(client,report);await targetChecksums(client,report);}await client.query(options.dryRun===true?"ROLLBACK":"COMMIT");return report;}catch(cause){await client.query("ROLLBACK");throw cause;}finally{client.release();source.close();}}
function hasTable(db:Database.Database,table:string){return db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table)!==undefined;}
async function insertRow(client:PoolClient,table:string,row:Record<string,unknown>,targetColumns:ReadonlySet<string>){const enriched=table==="accounts"?{...row,max_concurrency:row["max_concurrency"]??5,health_status:row["health_status"]??"unknown"}:row;const rename:Record<string,string>={allowed_modes_json:"allowed_modes",allowed_models_json:"allowed_models",allowed_resolutions_json:"allowed_resolutions",scopes_json:"scopes_json",result_json:"result_json",payload_json:"payload_json",baseline_json:"baseline_json"};const entries=Object.entries(enriched).filter(([,value])=>value!==undefined).map(([key,value])=>[rename[key]??key,value]as const).filter(([key])=>targetColumns.has(key)),columns=entries.map(([key])=>key),values=entries.map(([key,value])=>normalize(table,key,value)),params=values.map((_,index)=>`$${String(index+1)}`);await client.query(`INSERT INTO ${table}(${columns.join(",")}) VALUES(${params.join(",")}) ON CONFLICT DO NOTHING`,values);}
const BOOLEAN_COLUMNS=new Set(["enabled","quote_known"]);const JSON_COLUMNS=new Set(["allowed_modes","allowed_models","allowed_resolutions","scopes_json","result_json","payload_json","baseline_json"]);function normalize(_table:string,column:string,value:unknown){if(Buffer.isBuffer(value))return value.toString("hex");if(BOOLEAN_COLUMNS.has(column)&&typeof value==="number"&&(value===0||value===1))return value===1;if(JSON_COLUMNS.has(column)&&typeof value==="string"){try{return JSON.stringify(JSON.parse(value)as unknown);}catch{throw new Error(`Invalid JSON in ${_table}.${column}`);}}return value;}
async function assertEmptyTarget(client:PoolClient){for(const table of TABLES){const result=await client.query<{count:string}>(`SELECT COUNT(*) count FROM ${table}`),count=Number(result.rows[0]?.count??0),allowed=table==="users"||table==="plans"||table==="projects"||table==="accounts"?1:0;if(count>allowed)throw new Error(`Target table ${table} is not empty`);}}
async function targetChecksums(client:PoolClient,report:MigrationReport){for(const table of TABLES){const rows=(await client.query<Record<string,unknown>>(`SELECT * FROM ${table} ORDER BY 1`)).rows;report.targetChecksums[table]=createHash("sha256").update(JSON.stringify(rows)).digest("hex");}}
async function validate(client:PoolClient,report:MigrationReport){for(const[table,expected]of Object.entries(report.tables)){const result=await client.query<{count:string}>(`SELECT COUNT(*) count FROM ${table}`),actual=Number(result.rows[0]?.count??0);if(actual<expected)throw new Error(`Migration count mismatch for ${table}: ${String(actual)} < ${String(expected)}`);}}
