import { createHmac, randomBytes } from "node:crypto";
import type { SqliteStore } from "../persistence/sqlite-store.js";
export interface WebhookEndpoint{id:string;projectId:string;url:string;secret:string;enabled:boolean;}
export interface WebhookEvent{id:string;projectId:string;jobId:string;eventType:"video.completed"|"video.failed"|"video.unknown";payload:string;attempts:number;nextAttemptAt:number;status?:"pending"|"delivered"|"dead";lastError?:string|null;deliveredAt?:number|null;createdAt?:number;}
export class SqliteWebhookRepository{
 constructor(private readonly store:SqliteStore,private readonly now:()=>number=Date.now){}
 configure(projectId:string,url:string):WebhookEndpoint{const parsed=new URL(url);if(parsed.protocol!=="https:")throw new TypeError("Webhook URL must use HTTPS");return this.store.immediate(db=>{const now=this.now(),id=`wh_${randomBytes(12).toString("hex")}`,secret=`whsec_${randomBytes(32).toString("base64url")}`;db.prepare(`INSERT INTO webhook_endpoints(id,project_id,url,secret,enabled,created_at,updated_at) VALUES(?,?,?,?,1,?,?) ON CONFLICT(project_id) DO UPDATE SET url=excluded.url,secret=excluded.secret,enabled=1,updated_at=excluded.updated_at`).run(id,projectId,url,secret,now,now);const row=db.prepare("SELECT id,project_id,url,secret,enabled FROM webhook_endpoints WHERE project_id=?").get(projectId) as {id:string;project_id:string;url:string;secret:string;enabled:number};return{id:row.id,projectId:row.project_id,url:row.url,secret:row.secret,enabled:row.enabled===1};});}
 list():WebhookEndpoint[]{return this.store.read(db=>(db.prepare("SELECT id,project_id,url,secret,enabled FROM webhook_endpoints ORDER BY created_at,id").all() as Array<{id:string;project_id:string;url:string;secret:string;enabled:number}>).map(row=>({id:row.id,projectId:row.project_id,url:row.url,secret:"",enabled:row.enabled===1})));}
 setEnabled(id:string,enabled:boolean):WebhookEndpoint{return this.store.immediate(db=>{if(db.prepare("UPDATE webhook_endpoints SET enabled=?,updated_at=? WHERE id=?").run(enabled?1:0,this.now(),id).changes!==1)throw new Error("Webhook endpoint not found");const row=db.prepare("SELECT id,project_id,url,secret,enabled FROM webhook_endpoints WHERE id=?").get(id) as {id:string;project_id:string;url:string;secret:string;enabled:number};return{id:row.id,projectId:row.project_id,url:row.url,secret:"",enabled:row.enabled===1};});}
 enqueue(jobId:string,eventType:WebhookEvent["eventType"],payload:object):void{this.store.immediate(db=>{const job=db.prepare("SELECT project_id FROM jobs WHERE id=?").get(jobId) as {project_id:string}|undefined;if(!job)throw new Error("Webhook job not found");const endpoint=db.prepare("SELECT 1 FROM webhook_endpoints WHERE project_id=? AND enabled=1").get(job.project_id);if(!endpoint)return;const now=this.now();db.prepare(`INSERT INTO webhook_outbox(id,project_id,job_id,event_type,payload_json,status,next_attempt_at,created_at,updated_at) VALUES(?,?,?,?,?,'pending',?,?,?) ON CONFLICT(job_id,event_type) DO NOTHING`).run(`evt_${randomBytes(16).toString("hex")}`,job.project_id,jobId,eventType,JSON.stringify(payload),now,now,now);});}
 due(limit=20):Array<WebhookEvent&{url:string;secret:string}>{return this.store.read(db=>(db.prepare(`SELECT o.id,o.project_id,o.job_id,o.event_type,o.payload_json,o.attempts,o.next_attempt_at,e.url,e.secret FROM webhook_outbox o JOIN webhook_endpoints e ON e.project_id=o.project_id WHERE o.status='pending' AND o.next_attempt_at<=? AND e.enabled=1 ORDER BY o.next_attempt_at LIMIT ?`).all(this.now(),limit) as Array<{id:string;project_id:string;job_id:string;event_type:WebhookEvent["eventType"];payload_json:string;attempts:number;next_attempt_at:number;url:string;secret:string}>).map(r=>({id:r.id,projectId:r.project_id,jobId:r.job_id,eventType:r.event_type,payload:r.payload_json,attempts:r.attempts,nextAttemptAt:r.next_attempt_at,url:r.url,secret:r.secret})));}
 deliveries(limit=100):WebhookEvent[]{return this.store.read(db=>(db.prepare("SELECT id,project_id,job_id,event_type,payload_json,status,attempts,next_attempt_at,last_error,delivered_at,created_at FROM webhook_outbox ORDER BY created_at DESC LIMIT ?").all(limit) as Array<{id:string;project_id:string;job_id:string;event_type:WebhookEvent["eventType"];payload_json:string;status:"pending"|"delivered"|"dead";attempts:number;next_attempt_at:number;last_error:string|null;delivered_at:number|null;created_at:number}>).map(r=>({id:r.id,projectId:r.project_id,jobId:r.job_id,eventType:r.event_type,payload:r.payload_json,status:r.status,attempts:r.attempts,nextAttemptAt:r.next_attempt_at,lastError:r.last_error,deliveredAt:r.delivered_at,createdAt:r.created_at})));}
 replay(id:string):void{this.store.immediate(db=>{if(db.prepare("UPDATE webhook_outbox SET status='pending',attempts=0,next_attempt_at=?,last_error=NULL,delivered_at=NULL,updated_at=? WHERE id=? AND status='dead'").run(this.now(),this.now(),id).changes!==1)throw new Error("Dead webhook event not found");});}
 delivered(id:string):void{this.store.immediate(db=>db.prepare("UPDATE webhook_outbox SET status='delivered',delivered_at=?,updated_at=? WHERE id=? AND status='pending'").run(this.now(),this.now(),id));}
 failed(id:string,error:string):void{this.store.immediate(db=>{const row=db.prepare("SELECT attempts FROM webhook_outbox WHERE id=?").get(id) as {attempts:number}|undefined;if(!row)return;const attempts=row.attempts+1,dead=attempts>=8,delay=Math.min(3600000,1000*2**Math.min(attempts,10));db.prepare("UPDATE webhook_outbox SET status=?,attempts=?,next_attempt_at=?,last_error=?,updated_at=? WHERE id=?").run(dead?"dead":"pending",attempts,this.now()+delay,error.slice(0,500),this.now(),id);});}
 sign(secret:string,timestamp:number,payload:string):string{return createHmac("sha256",secret).update(`${String(timestamp)}.${payload}`).digest("hex");}
}
